enable tests, etc...

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -15,26 +15,26 @@ jobs:
       fail-fast: false
       matrix:
         os:
-          # - "ubuntu-18.04"
+          - "ubuntu-18.04"
           - "ubuntu-20.04"
-          # - "windows-2019"
+          - "windows-2019"
         node-version:
           - 14
-        # e2e-tests: # TODO (Eli 10/5/20): figure out a more robust way to ensure all subfolders are covered (maybe using the fixture.meta flag and a pre-commit hook to ensure all tests have one...or with the file glob pattern...)
-        #   # - "tests/e2e/playback"
-        #   # - "tests/e2e/status"
-        #   # - "tests/e2e/waveforms"
-        #   # - "tests/e2e/settings"
-        #   # - "tests/e2e/basic_widgets"
-        #   # - "tests/e2e/plate_based_widgets"
-        # include:
-        #   # only enable coverage on the fastest job
-        #   - os: "ubuntu-20.04"
-        #     node: "14"
-        #     e2e-tests: "tests/e2e/status"
-        #     IS_FASTEST_JOB: true
-        #   - e2e-tests: "tests/e2e/status"
-        #     IS_FASTEST_E2E_SUITE: true
+        e2e-tests: # TODO (Eli 10/5/20): figure out a more robust way to ensure all subfolders are covered (maybe using the fixture.meta flag and a pre-commit hook to ensure all tests have one...or with the file glob pattern...)
+          - "tests/e2e/playback"
+          - "tests/e2e/status"
+          - "tests/e2e/waveforms"
+          - "tests/e2e/settings"
+          - "tests/e2e/basic_widgets"
+          - "tests/e2e/plate_based_widgets"
+        include:
+          # only enable coverage on the fastest job
+          - os: "ubuntu-20.04"
+            node: "14"
+            e2e-tests: "tests/e2e/status"
+            IS_FASTEST_JOB: true
+          - e2e-tests: "tests/e2e/status"
+            IS_FASTEST_E2E_SUITE: true
 
     name: Test code before publishing in Node ${{ matrix.node-version }} on ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
@@ -77,17 +77,17 @@ jobs:
           echo "SHA of main branch: ${{ steps.extract_branch.outputs.sha-of-main-branch }}"
           echo "SHA of development branch: ${{ steps.extract_branch.outputs.sha-of-development-branch }}"
 
-      # - name: Is this running on development branch?
-      #   if: runner.os == 'Linux'
-      #   run: if [ "${{ steps.extract_branch.outputs.sha-of-current-branch}}" = "${{ steps.extract_branch.outputs.sha-of-development-branch}}" ] ; then echo "Running on development branch."; else echo "Not running on development branch."; fi
+      - name: Is this running on development branch?
+        if: runner.os == 'Linux'
+        run: if [ "${{ steps.extract_branch.outputs.sha-of-current-branch}}" = "${{ steps.extract_branch.outputs.sha-of-development-branch}}" ] ; then echo "Running on development branch."; else echo "Not running on development branch."; fi
 
-      # - name: Is this running on main branch?
-      #   if: runner.os == 'Linux'
-      #   run: if [ "${{ steps.extract_branch.outputs.sha-of-current-branch}}" = "${{ steps.extract_branch.outputs.sha-of-main-branch}}" ] ; then echo "Running on main branch."; else echo "Not running on main branch."; fi
+      - name: Is this running on main branch?
+        if: runner.os == 'Linux'
+        run: if [ "${{ steps.extract_branch.outputs.sha-of-current-branch}}" = "${{ steps.extract_branch.outputs.sha-of-main-branch}}" ] ; then echo "Running on main branch."; else echo "Not running on main branch."; fi
 
-      # - name: Fail if attempting to publish from a branch other than main
-      #   if: runner.os == 'Linux' && github.event.inputs.publish_package == '1'
-      #   run: if [ "${{ steps.extract_branch.outputs.sha-of-current-branch}}" = "${{ steps.extract_branch.outputs.sha-of-main-branch}}" ] ; then echo "Running on main branch, can proceed to publish."; else exit 1; fi
+      - name: Fail if attempting to publish from a branch other than main
+        if: runner.os == 'Linux' && github.event.inputs.publish_package == '1'
+        run: if [ "${{ steps.extract_branch.outputs.sha-of-current-branch}}" = "${{ steps.extract_branch.outputs.sha-of-main-branch}}" ] ; then echo "Running on main branch, can proceed to publish."; else exit 1; fi
 
       - name: Set up Python for use with pre-commit
         uses: actions/setup-python@v2
@@ -105,15 +105,15 @@ jobs:
           node --version
           npm --version
 
-      # - name: Display Chrome version (Windows)
-      #   if: runner.os == 'Windows'
-      #   run: (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo
+      - name: Display Chrome version (Windows)
+        if: runner.os == 'Windows'
+        run: (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo
 
-      # - name: Display Chrome version (Linux)
-      #   if: runner.os == 'Linux'
-      #   run: |
-      #     google-chrome --version
-      #     chromedriver --version
+      - name: Display Chrome version (Linux)
+        if: runner.os == 'Linux'
+        run: |
+          google-chrome --version
+          chromedriver --version
 
       - name: Cache node modules # https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
         uses: actions/cache@v2.1.6
@@ -167,23 +167,23 @@ jobs:
         if: matrix.IS_FASTEST_E2E_SUITE == true
         run: npm run test:unit-no-prebuild -- --ci --verbose
 
-      # - name: Run E2E Tests (Linux)
-      #   if: runner.os == 'Linux'
-      #   uses: CuriBio/testcafe-action@v0.0.4
-      #   with:
-      #     skip-install: true
-      #     args: '"chrome:headless:emulation:width=1920;height=930;cdpPort=9223;" ${{ matrix.e2e-tests }} --screenshots path=./tests/e2e/screenshots --app ''node ./node_modules/@curi-bio/frontend-test-utils/src/check_engines.js && cross-env-shell NODE_ENV=development nuxt dev --spa'' --app-init-delay 45000'
+      - name: Run E2E Tests (Linux)
+        if: runner.os == 'Linux'
+        uses: CuriBio/testcafe-action@v0.0.4
+        with:
+          skip-install: true
+          args: '"chrome:headless:emulation:width=1920;height=930;cdpPort=9223;" ${{ matrix.e2e-tests }} --screenshots path=./tests/e2e/screenshots --app ''node ./node_modules/@curi-bio/frontend-test-utils/src/check_engines.js && cross-env-shell NODE_ENV=development nuxt dev --spa'' --app-init-delay 45000'
 
-      # - name: Confirm Sphinx Docs build correctly
-      #   # only check Sphinx docs build on the fastest job
-      #   if: matrix.IS_FASTEST_JOB == true
-      #   run: SPHINXOPTS="-W" make --directory=docs html # the -W flag treats warnings as errors to cause build failures
+      - name: Confirm Sphinx Docs build correctly
+        # only check Sphinx docs build on the fastest job
+        if: matrix.IS_FASTEST_JOB == true
+        run: SPHINXOPTS="-W" make --directory=docs html # the -W flag treats warnings as errors to cause build failures
 
-      # - name: Confirm no modifications to the repository files occurred when running the test suite
-      #   if: matrix.IS_FASTEST_JOB == true # only enable pre-commit on the fastest job
-      #   env:
-      #     PRE_COMMIT_HOME: ./.precommit_cache
-      #   run: pre-commit run git-dirty -a
+      - name: Confirm no modifications to the repository files occurred when running the test suite
+        if: matrix.IS_FASTEST_JOB == true # only enable pre-commit on the fastest job
+        env:
+          PRE_COMMIT_HOME: ./.precommit_cache
+        run: pre-commit run git-dirty -a
 
       # - name: Confirm can install in other directory # https://docs.npmjs.com/cli/v6/using-npm/developers
       #   run: |
@@ -194,12 +194,12 @@ jobs:
           name: dist--${{ matrix.os }}--${{ matrix.node-version }}
           path: dist/*
 
-      # - name: Archive visual regression
-      #   if: ${{ failure() }}
-      #   uses: actions/upload-artifact@v2
-      #   with:
-      #     name: visual-regression-screenshots--${{ matrix.os }}--${{ matrix.node }}
-      #     path: "tests/e2e/screenshots/**/*"
+      - name: Archive visual regression
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: visual-regression-screenshots--${{ matrix.os }}--${{ matrix.node }}
+          path: "tests/e2e/screenshots/**/*"
 
   publish_package:
     needs: [test]
@@ -259,11 +259,11 @@ jobs:
         # not sure why CodeBuild fails without the --unsafe-perm flag for npm ci, but it seems to help when running the "prepare" scripts after the install https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd
         run: |
           npm ci --unsafe-perm --cache .npm_cache/
-          #pip freeze
+          pip freeze
 
       - name: Uploading to NPM (if publishing)
         if: github.event.inputs.publish_package == '1'
-        run: npm publish --verbose --access public
+        run: npm publish --access public
 
       - name: Uploading to NPM (if dry run)
         if: github.event.inputs.publish_package != '1'
